# version: '3.3' # for CentOS7
version: "3.9"
services:
  server:
    image: 
      khedmatkar:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    entrypoint:
      "java -jar /khedmatkar/demo-0.0.1-SNAPSHOT.jar"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: khedmatkar

    restart: always
    ports:
      - 5432:5432

